"""Пакет prompts: тексты промптов и настроек мира, вынесенные из main.py (Фаза A).

Реэкспортирует прежние имена, чтобы остальной код бота не требовал правок.
"""
from __future__ import annotations

from .control_block import CONTROL_BLOCK_INSTRUCTIONS
from .creation import (
    HERO_ALREADY_CONFIRMED_ALERT,
    HERO_ALREADY_CONFIRMED_TEXT,
    HERO_CARD_QUESTION,
    HERO_CARD_TITLE_CREATED,
    HERO_CARD_TITLE_PENDING,
    HERO_CARD_TITLE_RANDOM,
    HERO_CREATION_PROMPT,
    HERO_CREATION_START_PROMPT,
    HERO_NOT_CREATED_ALERT,
    HERO_SETTING_FIRST_NOTE,
    WARCRAFT_CREATION_ADDENDUM,
)
from .dm_prompt import BASE_DM_PROMPT
from .settings import (
    DM_ROLL_INSTRUCTION,
    SETTING_CONFIRM_DND,
    SETTING_CONFIRM_WARCRAFT,
    SETTING_MENU_TEXT,
    SETTING_SWITCHED_TEXT,
    WARCRAFT_LORE_MISSING_NOTE,
    WARCRAFT_LORE_PROMPT,
    WARCRAFT_SETTING_INTRO,
    WARCRAFT_SETTING_OUTRO,
)

__all__ = [
    "BASE_DM_PROMPT",
    "CONTROL_BLOCK_INSTRUCTIONS",
    "DM_ROLL_INSTRUCTION",
    "HERO_ALREADY_CONFIRMED_ALERT",
    "HERO_ALREADY_CONFIRMED_TEXT",
    "HERO_CARD_QUESTION",
    "HERO_CARD_TITLE_CREATED",
    "HERO_CARD_TITLE_PENDING",
    "HERO_CARD_TITLE_RANDOM",
    "HERO_CREATION_PROMPT",
    "HERO_CREATION_START_PROMPT",
    "HERO_NOT_CREATED_ALERT",
    "HERO_SETTING_FIRST_NOTE",
    "SETTING_CONFIRM_DND",
    "SETTING_CONFIRM_WARCRAFT",
    "SETTING_MENU_TEXT",
    "SETTING_SWITCHED_TEXT",
    "WARCRAFT_CREATION_ADDENDUM",
    "WARCRAFT_LORE_MISSING_NOTE",
    "WARCRAFT_LORE_PROMPT",
    "WARCRAFT_SETTING_INTRO",
    "WARCRAFT_SETTING_OUTRO",
]
